# Generated by Django 4.0.4 on 2022-06-30 17:04

from django.db import migrations, models
import wtsApi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=-1)),
                ('chat_type', models.TextField(choices=[('group', 'group'), ('person', 'person')], default='person')),
                ('participants', models.TextField()),
                ('group_name', models.CharField(max_length=30)),
                ('group_description', models.CharField(max_length=150)),
                ('group_image_id', models.IntegerField(default=-1)),
                ('messages', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='imageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_usage', models.TextField(choices=[('post', 'post'), ('profile', 'profile'), ('group_image', 'group_photo')], default='post')),
                ('upload', models.ImageField(upload_to=wtsApi.models.user_directory_path)),
                ('image_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('time_created', models.TextField(default='2020')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='usersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('user_id', models.IntegerField(default=-1)),
                ('bio', models.TextField(default='Hey there! I am using WhatsApp')),
                ('profile_image_id', models.IntegerField(default=-1)),
                ('user_chats_id', models.TextField()),
            ],
        ),
    ]
