# Generated by Django 4.0.4 on 2022-07-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtsApi', '0006_alter_filebox_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebox',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
